# Generated by Django 3.0.3 on 2020-03-24 08:10

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import utils.shortcuts


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(null=True)),
                ('log_type', models.TextField()),
                ('explain', models.TextField()),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField(encoder=utils.shortcuts.MyJSONEncoder)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
