# Generated by Django 3.0.3 on 2020-03-24 08:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_name', models.CharField(max_length=100, null=True)),
                ('now_name', models.CharField(max_length=32)),
                ('image_type', models.CharField(default='other', max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
