version: "3"
services:
  postgres:
    image: postgres:12.0
    container_name: ms_postgres
    restart: always
    # ports:
    # - "5432:5432/tcp"
    environment:
      POSTGRES_DB: magicstyle
      POSTGRES_PASSWORD: "magicstyle"
      POSTGRES_USER: magicstyle
    volumes:
      - "./postgresql:/var/lib/postgresql/data"
  server:
    image: ms_server:latest
    container_name: ms_server
    restart: always
    # ports:
    #   - 8000:8000
    depends_on:
      - postgres
    volumes:
      - "./log/server:/web/log"
      - "./images/style_image:/dev/resources/images/style_image"
      - "./images/style_image_fortrain:/dev/resources/images/style_image_fortrain"
      - "./images/upload_image:/dev/resources/images/upload_image"
      - "./images/generate_image:/dev/resources/images/generate_image"
      - "./images/other_image:/dev/resources/images/other_image"
      - "./download:/dev/resources/download"
    healthcheck:
      test: "curl -fs http://127.0.0.1:8000/api/CSRFTokenAPI || exit 1"
      interval: 60s
      timeout: 10s
  openresty:
    image: ms_openresty:latest
    container_name: ms_openresty
    restart: always
    ports:
      - 80:80
      - 443:443
    depends_on:
      - postgres
      - server
    volumes:
      - "./log/openresty:/web/nginx/logs"
      - "./images/style_image:/dev/resources/images/style_image"
      - "./images/style_image_fortrain:/dev/resources/images/style_image_fortrain"
      - "./images/upload_image:/dev/resources/images/upload_image"
      - "./images/generate_image:/dev/resources/images/generate_image"
      - "./other_image:/dev/resources/other_image"
  style_migrate:
    image: ms_style_migrate:latest
    container_name: ms_style_migrate
    restart: always
    # ports:
    #  - 1600:1600
    volumes:
      - "./images/style_image:/dev/resources/images/style_image"
      - "./images/original_image:/dev/resources/images/upload_image"
      - "./images/generate_image:/dev/resources/images/generate_image"
      - "./model:/dev/resources/model"
      - "./data:/dev/resources/data"
      - "./migrate/vggnet:/dev/resources/vggnet"
      - "./migrate/MSCOCO:/dev/resources/MSCOCO"
  anime_style:
    image: ms_anime_style:latest
    container_name: ms_anime_style
    restart: always
    # ports:
    #  - 1600:1600
    volumes:
      - "./images/upload_image:/dev/resources/images/upload_image"
      - "./images/generate_images:/dev/resources/images/generate_image"
      - "./anime/checkpoint:/server/core/checkpoint"
      - "./anime/vgg19:/server/core/vgg19"

