# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc/style_migrate/style_migrate.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rpc/style_migrate/style_migrate.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n%rpc/style_migrate/style_migrate.proto\"+\n\x08Response\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"1\n\x0bLabelWeight\x12\x12\n\nimage_name\x18\x01 \x01(\t\x12\x0e\n\x06weight\x18\x02 \x01(\x02\"L\n\x10ImageLabelWeight\x12\x14\n\x0corigin_image\x18\x01 \x01(\t\x12\"\n\x0clabel_weight\x18\x02 \x03(\x0b\x32\x0c.LabelWeight\"D\n\rGenerateImage\x12\x1b\n\x08response\x18\x01 \x01(\x0b\x32\t.Response\x12\x16\n\x0egenerate_image\x18\x02 \x01(\t\"\x19\n\x06\x41\x63tion\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t2j\n\x0cStyleMigrate\x12%\n\rTrainingModel\x12\x07.Action\x1a\t.Response\"\x00\x12\x33\n\x0c\x43onvertImage\x12\x11.ImageLabelWeight\x1a\x0e.GenerateImage\"\x00\x62\x06proto3'
)




_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='Response.status', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=84,
)


_LABELWEIGHT = _descriptor.Descriptor(
  name='LabelWeight',
  full_name='LabelWeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_name', full_name='LabelWeight.image_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weight', full_name='LabelWeight.weight', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=135,
)


_IMAGELABELWEIGHT = _descriptor.Descriptor(
  name='ImageLabelWeight',
  full_name='ImageLabelWeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='origin_image', full_name='ImageLabelWeight.origin_image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='label_weight', full_name='ImageLabelWeight.label_weight', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=213,
)


_GENERATEIMAGE = _descriptor.Descriptor(
  name='GenerateImage',
  full_name='GenerateImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='GenerateImage.response', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='generate_image', full_name='GenerateImage.generate_image', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=283,
)


_ACTION = _descriptor.Descriptor(
  name='Action',
  full_name='Action',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='command', full_name='Action.command', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=310,
)

_IMAGELABELWEIGHT.fields_by_name['label_weight'].message_type = _LABELWEIGHT
_GENERATEIMAGE.fields_by_name['response'].message_type = _RESPONSE
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['LabelWeight'] = _LABELWEIGHT
DESCRIPTOR.message_types_by_name['ImageLabelWeight'] = _IMAGELABELWEIGHT
DESCRIPTOR.message_types_by_name['GenerateImage'] = _GENERATEIMAGE
DESCRIPTOR.message_types_by_name['Action'] = _ACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'rpc.style_migrate.style_migrate_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

LabelWeight = _reflection.GeneratedProtocolMessageType('LabelWeight', (_message.Message,), {
  'DESCRIPTOR' : _LABELWEIGHT,
  '__module__' : 'rpc.style_migrate.style_migrate_pb2'
  # @@protoc_insertion_point(class_scope:LabelWeight)
  })
_sym_db.RegisterMessage(LabelWeight)

ImageLabelWeight = _reflection.GeneratedProtocolMessageType('ImageLabelWeight', (_message.Message,), {
  'DESCRIPTOR' : _IMAGELABELWEIGHT,
  '__module__' : 'rpc.style_migrate.style_migrate_pb2'
  # @@protoc_insertion_point(class_scope:ImageLabelWeight)
  })
_sym_db.RegisterMessage(ImageLabelWeight)

GenerateImage = _reflection.GeneratedProtocolMessageType('GenerateImage', (_message.Message,), {
  'DESCRIPTOR' : _GENERATEIMAGE,
  '__module__' : 'rpc.style_migrate.style_migrate_pb2'
  # @@protoc_insertion_point(class_scope:GenerateImage)
  })
_sym_db.RegisterMessage(GenerateImage)

Action = _reflection.GeneratedProtocolMessageType('Action', (_message.Message,), {
  'DESCRIPTOR' : _ACTION,
  '__module__' : 'rpc.style_migrate.style_migrate_pb2'
  # @@protoc_insertion_point(class_scope:Action)
  })
_sym_db.RegisterMessage(Action)



_STYLEMIGRATE = _descriptor.ServiceDescriptor(
  name='StyleMigrate',
  full_name='StyleMigrate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=312,
  serialized_end=418,
  methods=[
  _descriptor.MethodDescriptor(
    name='TrainingModel',
    full_name='StyleMigrate.TrainingModel',
    index=0,
    containing_service=None,
    input_type=_ACTION,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ConvertImage',
    full_name='StyleMigrate.ConvertImage',
    index=1,
    containing_service=None,
    input_type=_IMAGELABELWEIGHT,
    output_type=_GENERATEIMAGE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STYLEMIGRATE)

DESCRIPTOR.services_by_name['StyleMigrate'] = _STYLEMIGRATE

# @@protoc_insertion_point(module_scope)
