# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from rpc.style_migrate import style_migrate_pb2 as rpc_dot_style__migrate_dot_style__migrate__pb2


class StyleMigrateStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TrainingModel = channel.unary_unary(
        '/StyleMigrate/TrainingModel',
        request_serializer=rpc_dot_style__migrate_dot_style__migrate__pb2.Action.SerializeToString,
        response_deserializer=rpc_dot_style__migrate_dot_style__migrate__pb2.Response.FromString,
        )
    self.ConvertImage = channel.unary_unary(
        '/StyleMigrate/ConvertImage',
        request_serializer=rpc_dot_style__migrate_dot_style__migrate__pb2.ImageLabelWeight.SerializeToString,
        response_deserializer=rpc_dot_style__migrate_dot_style__migrate__pb2.GenerateImage.FromString,
        )


class StyleMigrateServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TrainingModel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ConvertImage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_StyleMigrateServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TrainingModel': grpc.unary_unary_rpc_method_handler(
          servicer.TrainingModel,
          request_deserializer=rpc_dot_style__migrate_dot_style__migrate__pb2.Action.FromString,
          response_serializer=rpc_dot_style__migrate_dot_style__migrate__pb2.Response.SerializeToString,
      ),
      'ConvertImage': grpc.unary_unary_rpc_method_handler(
          servicer.ConvertImage,
          request_deserializer=rpc_dot_style__migrate_dot_style__migrate__pb2.ImageLabelWeight.FromString,
          response_serializer=rpc_dot_style__migrate_dot_style__migrate__pb2.GenerateImage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'StyleMigrate', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
