# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from rpc import anime_style_pb2 as rpc_dot_anime__style__pb2


class AnimeStyleStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ConvertAnimeStyle = channel.unary_unary(
        '/AnimeStyle/ConvertAnimeStyle',
        request_serializer=rpc_dot_anime__style__pb2.Image.SerializeToString,
        response_deserializer=rpc_dot_anime__style__pb2.Image.FromString,
        )


class AnimeStyleServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ConvertAnimeStyle(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AnimeStyleServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ConvertAnimeStyle': grpc.unary_unary_rpc_method_handler(
          servicer.ConvertAnimeStyle,
          request_deserializer=rpc_dot_anime__style__pb2.Image.FromString,
          response_serializer=rpc_dot_anime__style__pb2.Image.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AnimeStyle', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
